### PR TITLE
Support for before_each and after_each

### PR DESCRIPTION
**Pull request by jozip**
I thought it would be handy to be able to run stuff before and after each test case (something akin to around-filters in CLOS).

### CODE REVIEW

**Comment by jozip** [comment]
After a good night's sleep, I can also add that

- The filters are local to the current description/subdesc (which I think makes sense since a sub-component are likely to have its own resources.)
- You can only have one active pair, per description/subdesc, at a time (i.e. they don't stack and unwind accordingly.)
- You can arrange so that a subset of the tests that have no associated resources don't run the around-filters by simply placing them above the filter-declarations or by adding empty declarations above.

I had initially thought of having the around-filters stack horizontally (within a description/subdesc) and vertically (across descriptions/subdescs), but it got a lot more complicated for little gain. That's the reason the variable `_snow_lables` got changed to `_snow_defer_labels`; to distinguish between the various label-sets. I left it in since it makes the intention a little bit clearer.

**Comment by mortie** [comment]
This looks pretty good. I'm thinking that some form of stacking could make sense, but execution is already jumping around a ton with defers (and between macros with those block arguments), so it's probably good to not add `before_each`/`after_each` stacking on top. This will take care of the simpler use cases, where more complex use cases can always fall back on a combination of `before_each`/`after_each` and macros for setup and teardown.

My only concern is that in order for using the `it` macro to make sense, you have to introduce a new `subdesc` to specify what the "it" refers to (grammatically speaking). Until now, that has made no difference, but with this patch, there's a lot of friction in creating a new subdesc, because you may have to copy a long `before_each` or `after_each` into the subdesc. Maybe it should behave more like variable scoping, where the `before_each` or `after_each` applies to all subdescs, however deeply nested they are, until they're overwritten?

Example: this code should work:

```
describe(vector, {
    vector vec;
    before_each({ vector_init(&vec); });
    after_each({ vector_free(&vec); });

    it("inits with a count of 0", { asserteq(vec.count, 0); });

    subdesc(vector_get, {
        before_each({
            vector_init(&vec);
            int var = 10;
            vector_set(&vec, 0, &var);
        });

        // Notice: no after_each, because the parent desc's after_each still applies

        it("gets the first value", {
            int var = *(int *)vector_get(&vec, 0);
            asserteq(var, 10);
        });
    });
});
```

(On an unrelated note: just imagine how much cleaner and easier all of this would've been to implement if the C preprocessor was a proper procedural and turing-complete language...)

**Comment by jozip** [comment]
Ever played with M4? :)

I agree, though I think it's a matter of style. For instance, in the project I'm working on, I got a module where I got a set of auxiliary routines that are tightly associated with the module itself. I.e., it makes little sense in having them have their own root describe, and yet they have their own distinct resource allocators. My proposal fits that use case nicely -- although no more, no less.

Your proposal is a nice compromise between power and simplicity; clear semantics while still being able to cater to varying needs. And I don't think it need to be complicated to achieve either: just keep two stacks in the describe, one for `before_each`-clauses and one for `after_each`. Every test case peeks at the top of respective stack to execute the correct clauses, and every `subdesc` pushes a new frame.

**Comment by jozip** [comment]
Well look at that... Segfaults! This is weird, since the build passes nicely on my machine

**Comment by jozip** [comment]
Oh, hell yeah! And here I was mucking about in an ancient GDB on a virtual machine :)

**Comment by mortie** [comment]
This looks good, I'll review it more thoroughly later today and probably merge it.

**Pull request merged**
