### PR TITLE
Run specific test

### PR DESCRIPTION
**Pull request by jozip**
This implements a way of specifying a single describe to run, making it easier to use in a larger project.

### CODE REVIEW

**Comment by jozip** [comment]
I also took the liberty to add an editorconfig-file so that future contributers don't get tripped up :)

**Comment by mortie** [comment]
Adding an editorconfig file is a great idea. I see I haven't paid enough attention to whether PRs indent stuff correctly, I'll pay more attention to that in the future - thanks for noticing :) (Ironically though, some of the lines you added are indented with spaces instead of tabs.)

I like the idea of beign able to specify what tests to run, but I think it should be possible to specify multiple tests (i.e `./test-whatever foo bar baz` to run the tests `foo`, `bar`, and `baz`).

**Comment by jozip** [comment]
Ah, I saw that just now. Fixed.

I threw in support for specifying multiple tests for good measure. Bored at work, you see.

**Comment by mortie** [comment]
That looks great, merging.

**Pull request merged**
